services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: "postgresql://username:password@postgres:5432/db_name"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
